version: '3.3'

services:
  backend:
    container_name: python-flaskrestapi-backend
    build:
      context: .
      dockerfile: Dockerfile  # Replace with your Dockerfile name if different
    ports:
      - "5000:5000"
    command: flask run --host 0.0.0.0
    volumes:
      - .:/app

  db:
    image: mongo:latest
    container_name: mongo-db1
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: